include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    # Effective Dart: Style
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names

    # Effective Dart: Documentation
    - slash_for_doc_comments
    - package_api_docs

    # Effective Dart: Usage
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - unnecessary_getters_setters
    - prefer_expression_function_bodies
    - unnecessary_this
    - prefer_initializing_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catches_without_on_clauses
    - use_rethrow_when_possible

    # Effective Dart: Design
    - use_to_and_as_if_applicable
    - one_member_abstracts
    - avoid_classes_with_only_static_members
    - prefer_final_fields
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_this
    - type_annotate_public_apis
    - avoid_types_on_closure_parameters
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions
    - use_function_type_syntax_for_parameters
    - avoid_positional_boolean_parameters
    - hash_and_equals
    - avoid_null_checks_in_equality_operators

    # Flutter specific
    - use_key_in_widget_constructors
    - use_full_hex_values_for_flutter_colors
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_decorated_box

    # Additional rules
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - collection_methods_unrelated_type
    - curly_braces_in_flow_control_structures
    - empty_catches
    - exhaustive_cases
    - no_duplicate_case_values
    - null_closures
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_if_null_operators
    - prefer_inlined_adds
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - recursive_getters
    - sort_child_properties_last
    - throw_in_finally
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - valid_regexps
