// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Project: easy-mode-coach
/// Console: https://console.firebase.google.com/project/easy-mode-coach/overview
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0q_7vFAgoY_bqa66iYNgrfMOK2UrS1Tg',
    appId: '1:190696117404:web:f1edb4383b794678808959',
    messagingSenderId: '190696117404',
    projectId: 'easy-mode-coach',
    authDomain: 'easy-mode-coach.firebaseapp.com',
    storageBucket: 'easy-mode-coach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS7GXKheeMVzT2BVaH2EfDx0kXwaaJMsY',
    appId: '1:190696117404:android:ea55037c4bcd29aa808959',
    messagingSenderId: '190696117404',
    projectId: 'easy-mode-coach',
    storageBucket: 'easy-mode-coach.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcvHwPiTHvMr50z9zv-qneMWAYV-eR9-w',
    appId: '1:190696117404:ios:d4524987f9ff49f4808959',
    messagingSenderId: '190696117404',
    projectId: 'easy-mode-coach',
    storageBucket: 'easy-mode-coach.firebasestorage.app',
    iosBundleId: 'com.easymode.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcvHwPiTHvMr50z9zv-qneMWAYV-eR9-w',
    appId: '1:190696117404:ios:d4524987f9ff49f4808959',
    messagingSenderId: '190696117404',
    projectId: 'easy-mode-coach',
    storageBucket: 'easy-mode-coach.firebasestorage.app',
    iosBundleId: 'com.easymode.app',
  );
}
