-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgffR6Bzofyal+7GmU
mNlfni21b3R98EJkEhEVBPyc2iagCgYIKoZIzj0DAQehRANCAAR9zYO+vHEgtPvF
Q5PmyPo8ZnhJMp7ylsaglraSNMLS1XM2ijGN0s5XmaQZZuh8LKLZxNOyLeaUKrcK
tagyzzfE
-----END PRIVATE KEY-----
